---
#driver:
#  name: docker
#  binary: /usr/bin/docker
#  use_sudo: false
#  require_chef_omnibus: true
driver:
  name: dokken
  privileged: true # adds support for running systemd

provisioner:
  name: dokken
  environments_path: environments
  roles_path: roles

transport:
  name: dokken
  #name: ssh
  #username: kitchen

platforms:
  - name: centos-7.2
    driver:
      image: centos:7
      pid_one_command: /usr/lib/systemd/systemd
#      intermediate_instructions:
#        - RUN /usr/bin/yum install -y initscripts        

verifier:
  name: inspec
  root_path: '/opt/verifier'  
  profiles_path: test/integration/profiles  
  sudo: false
  format: progress

suites:
  - name: env-test
    provisioner:
      client_rb:
        environment: _default
        log_location: "/opt/kitchen/chef-client.log"
        log_level: :debug
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[bind9dns::install]
      - recipe[bind9dns::default]    